apiVersion: v1
kind: Namespace
metadata:
  name: stock-analysis-system
  labels:
    name: stock-analysis-system
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stock-analysis-quota
  namespace: stock-analysis-system
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: stock-analysis-limits
  namespace: stock-analysis-system
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container